services:
  container-copier-dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
        - ./:/workspace
        - container-copier-dev-vsc:/root/.vscode-server
    stdin_open: true
    tty: true

  fcbe-dev:
    build:
      context: ./src/fcbe
      dockerfile: Dockerfile.dev
    volumes:
        - ./src/fcbe:/workspace
        - fcbe-dev-vsc:/root/.vscode-server
    stdin_open: true
    tty: true

  fe-dev:
    build:
      context: ./src/fe
      dockerfile: Dockerfile.dev
    volumes:
        - ./src/fe:/workspace
        - fe-dev-vsc:/root/.vscode-server
    stdin_open: true
    tty: true

volumes:
  container-copier-dev-vsc:
  fcbe-dev-vsc:
  fe-dev-vsc: