services:
  gh-dev:
    build:
      context: ./src/gh
      dockerfile: Dockerfile.dev
    volumes:
        - ./src/gh:/workspace
        - gh-dev-vsc:/root/.vscode-server
    stdin_open: true
    tty: true

  fcbe-dev:
    build:
      context: ./src/fcbe
      dockerfile: Dockerfile.dev
    volumes:
        - ./src/fcbe:/workspace
        - fcbe-dev-vsc:/root/.vscode-server
    stdin_open: true
    tty: true

  fe-dev:
    build:
      context: ./src/fe
      dockerfile: Dockerfile.dev
    volumes:
        - ./src/fe:/workspace
        - fe-dev-vsc:/root/.vscode-server
    stdin_open: true
    tty: true

volumes:
  gh-dev-vsc:
  fcbe-dev-vsc:
  fe-dev-vsc: