name: copy
run-name: "Copy ${{ github.event.inputs.image }} ${{ github.event.inputs.platform }} to ACR"

on:
  workflow_dispatch:
    inputs:
      image:
        description: "image name, exp: mysql, ghcr.io/devcontainers/features/anaconda:1, ubuntu:18.04@sha256:98706f0f213dbd440021993a82d2f70451a73698315370ae8615cc468ac06624"
        required: true
      platform:
        description: 'container platform, exp: "linux/amd64"'
        required: false
        default: "linux/amd64"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Login to ACR with the AccessKey pair
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-hangzhou.aliyuncs.com
          username: "${{ secrets.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_PASSWORD }}"

      - name: Copy image
        run: |
          wget https://github.com/117503445/container-copier/releases/latest/download/copier && chmod +x copier && ./copier
        env:
          IMAGE: "${{ github.event.inputs.image }}"
          PLATFORM: "${{ github.event.inputs.platform }}"
