name: copy

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'registry(optional) & namespace, exp: "gcr.io/google_containers" "docker.io"'     
        required: true
      image:
        description: 'container name, exp: "pause"'     
        required: true
      tag:
        description: 'container tag'     
        required: false
        default: 'latest' 
      platform:
        description: 'container platform, exp: "linux/amd64"'     
        required: false
        default: 'linux/amd64'
env:
  OLDIMAGE: "${{ github.event.inputs.namespace }}/${{ github.event.inputs.image }}:${{ github.event.inputs.tag }}"
  NEWIMAGE: "registry.cn-hangzhou.aliyuncs.com/117503445-mirror/${{ github.event.inputs.image }}.{{ github.event.inputs.platform }}:${{ github.event.inputs.tag }}"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to ACR with the AccessKey pair
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-hangzhou.aliyuncs.com
          username: "${{ secrets.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_PASSWORD }}"

      - name: Build and push image to ACR
        run: |
          docker pull --platform "${{ github.event.inputs.platform }}" "$OLDIMAGE"
          docker tag "$OLDIMAGE" "$NEWIMAGE"
          docker push "$NEWIMAGE"
