name: copy

on:
  workflow_dispatch:
    inputs:
      full_image:
        description: 'full container name, exp: "gcr.io/google_containers/pause"'     
        required: true
      image:
        description: 'container name, exp: "pause"'     
        required: true
      tag:
        description: 'container tag'     
        required: false
        default: 'latest' 
env:
  REGION_ID: cn-hangzhou
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  NAMESPACE: 117503445-mirror
  FULLIMAGE: ${{ github.event.inputs.full_image }}
  IMAGE:  ${{ github.event.inputs.image }}
  TAG: ${{ github.event.inputs.tag }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to ACR with the AccessKey pair
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-hangzhou.aliyuncs.com
          username: "${{ secrets.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_PASSWORD }}"

      - name: Build and push image to ACR
        run: |
          docker pull "$FULLIMAGE"
          docker tag "$FULLIMAGE" "$REGISTRY/$NAMESPACE/$IMAGE:$TAG"
          docker push "$REGISTRY/$NAMESPACE/$IMAGE:$TAG"
